[package]
name = "client"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
bevy = { version = "0.16.0", features = ["dynamic_linking"] }
bevy_flycam = { git = 'https://github.com/kristoff3r/bevy_flycam/' }
shared = { path = "../shared" }

[profile.dev]
opt-level = 0
incremental = true
debug = true
